### ISSUE TITLE
commenting in webstorm

### ISSUE THREAD

**Issue by nekdolan** [modo-lv/LiveScriptBrains#3]
This plugin would be great for syntax highlighting in webstorm but because it doesn't include commenting (it seems) I simply cannot use it.
Since this is a plugin I cannot set the commenting for the file type *.ls . (Ctrl + /) which means I had to disable this plugin in the end.
Unfortunately I could not find any workarounds for this issue.

**Comment by modo-lv** [comment]
Fixed in 857582459eac45fce896088cc48dd489ef5e2484

**Comment by nekdolan** [comment]
Works as expected
thanks
